### ISSUE TITLE
Issue with installing electron-inspector

### ISSUE THREAD

**Issue by wenjunche** [enlight/electron-inspector#5]
Hello

I having an issue with running "npm install electron-inspector --save-dev" for electron-quick-start project.  Here are output:

npm WARN addRemoteGit Error: spawn git ENOENT
npm WARN addRemoteGit     at exports._errnoException (util.js:893:11)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
npm WARN addRemoteGit     at onErrorNT (internal/child_process.js:348:16)
npm WARN addRemoteGit     at _combinedTickCallback (internal/process/next_tick.js:74:11)
npm WARN addRemoteGit     at process._tickCallback (internal/process/next_tick.js:98:9)
npm WARN addRemoteGit  git://github.com/enlight/node-inspector.git#accd46758501d8187e55b32b54e3eff65c3fdaa3 resetting remote C:\Users\...\AppData\Roaming\npm-cache\_git-remotes\git-github-com-enlight-node-inspector-git-accd46758501d8187e55b32b54e3eff65c3fdaa3-ddd8c340 because of error: { [Error: spawn git ENOENT]
npm WARN addRemoteGit   code: 'ENOENT',
npm WARN addRemoteGit   errno: 'ENOENT',
npm WARN addRemoteGit   syscall: 'spawn git',
npm WARN addRemoteGit   path: 'git',
npm WARN addRemoteGit   spawnargs:
npm WARN addRemoteGit    [ '-c',
npm WARN addRemoteGit      'core.longpaths=true',
npm WARN addRemoteGit      'config',
npm WARN addRemoteGit      '--get',
npm WARN addRemoteGit      'remote.origin.url' ],
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm WARN addRemoteGit Error: spawn git ENOENT
npm WARN addRemoteGit     at exports._errnoException (util.js:893:11)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
npm WARN addRemoteGit     at onErrorNT (internal/child_process.js:348:16)
npm WARN addRemoteGit     at _combinedTickCallback (internal/process/next_tick.js:74:11)
npm WARN addRemoteGit     at process._tickCallback (internal/process/next_tick.js:98:9)
npm WARN addRemoteGit  git://github.com/enlight/v8-profiler.git#dc3a4e15f06dd6eaca705e69e235d21d5962eaf5 resetting remote C:\Users\...\AppData\Roaming\npm-cache\_git-remotes\git-github-com-enlight-v8-profiler-git-dc3a4e15f06dd6eaca705e69e235d21d5962eaf5-4c11d411 because of error: { [Error: spawn git ENOENT]
npm WARN addRemoteGit   code: 'ENOENT',
npm WARN addRemoteGit   errno: 'ENOENT',
npm WARN addRemoteGit   syscall: 'spawn git',
npm WARN addRemoteGit   path: 'git',
npm WARN addRemoteGit   spawnargs:
npm WARN addRemoteGit    [ '-c',
npm WARN addRemoteGit      'core.longpaths=true',
npm WARN addRemoteGit      'config',
npm WARN addRemoteGit      '--get',
npm WARN addRemoteGit      'remote.origin.url' ],
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm ERR! git clone --template=C:\Users\...\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/enlight/node-inspector.git C:\Users\...\AppData\Roaming\npm-cache\_git-remotes\git-github-com-enlight-node-inspector-git-accd46758501d8187e55b32b54e3eff65c3fdaa3-ddd8c340:
npm ERR! git clone --template=C:\Users\...\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/enlight/v8-profiler.git C:\Users\...\AppData\Roaming\npm-cache\_git-remotes\git-github-com-enlight-v8-profiler-git-dc3a4e15f06dd6eaca705e69e235d21d5962eaf5-4c11d411:
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "electron-inspector" "--save-dev"
npm ERR! node v5.12.0
npm ERR! npm  v3.8.6
npm ERR! path git
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn git

npm ERR! enoent spawn git ENOENT
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\...\Downloads\electron-quick-start\npm-debug.log

I have tried node 4.7.1 and 6.5.0 and got same error for both.

Thanks

**Comment by enlight** [comment]
Looks like NPM can't find Git, is Git accessible in the command prompt you run NPM from? If not you'll need to add it to your PATH.

**Comment by wenjunche** [comment]
Hello

Thank you for your response. 

Yes, git is accessible:

C:\Users\...\Downloads\electron-quick-start>git --version
git version 1.9.5.chromium.6

**Comment by wenjunche** [comment]
After sending the last comment, I realized it was using incorrect git.  So, I updated PATH and now it is able to install it.

But, when I tried running it, it is getting the following message:

C:\Users\...\Downloads\electron-quick-start>node_modules\.bin\electron-inspector
Electron not found.

I have the latest files from electron-quick-start repo.

Thanks
