### ISSUE TITLE
Can't run electron-inspector after installation due to missing yargs module.

### ISSUE THREAD

**Issue by kpatrick** [enlight/electron-inspector#6]
I installed electron-inspector on Windows 10. I then tried to run electron-inspector on a basic electron app that starts normally.  Here is the console log of the install and run failure. It looks like yargs doesn't install and isn't available.
```
Kyle@DevMachine C:\git\manymore
> npm install electron-inspector --save-dev
npm WARN package.json manymore@0.1.0 No README data
|
> v8-debug@0.7.7 preinstall C:\git\manymore\node_modules\electron-inspector\node_modules\v8-debug
> node -e 'process.exit(0)'


> v8-profiler@5.6.5 preinstall C:\git\manymore\node_modules\electron-inspector\node_modules\v8-profiler
> node -e 'process.exit(0)'

-
> v8-debug@0.7.7 install C:\git\manymore\node_modules\electron-inspector\node_modules\v8-debug
> node-pre-gyp install --fallback-to-build

[v8-debug] Success: "C:\git\manymore\node_modules\electron-inspector\node_modules\v8-debug\build\debug\v0.7.7\node-v46-win32-x64\debug.node" is installed via remote

> v8-profiler@5.6.5 install C:\git\manymore\node_modules\electron-inspector\node_modules\v8-profiler
> node-pre-gyp install --fallback-to-build

[v8-profiler] Success: "C:\git\manymore\node_modules\electron-inspector\node_modules\v8-profiler\build\profiler\v5.6.5\node-v46-win32-x64\profiler.node" is installed via remote
electron-inspector@0.1.4 node_modules\electron-inspector
├── v8-debug@0.7.7 (nan@2.5.0, node-pre-gyp@0.6.32)
├── node-inspector@0.12.8 (path-is-absolute@1.0.1, async@0.9.2, semver@4.3.6, serve-favicon@2.3.2, debug@2.6.0, which@1.2.12, strong-data-uri@1.0.4, ws@1.1.1, rc@1.1.6, glob@5.0.15, yargs@3.32.0, biased-opener@0.2.8)
└── v8-profiler@5.6.5 (nan@2.5.0, node-pre-gyp@0.6.32)

Kyle@DevMachine C:\git\manymore
> dir node_modules
 Volume in drive C is OSDisk
 Volume Serial Number is A62D-5055

 Directory of C:\git\manymore\node_modules

01/14/2017  05:13 PM    <DIR>          .
01/14/2017  05:13 PM    <DIR>          ..
01/14/2017  05:14 PM    <DIR>          .bin
01/13/2017  06:49 PM    <DIR>          bookshelf
01/13/2017  07:00 PM    <DIR>          devtron
01/13/2017  06:45 PM    <DIR>          electron
01/14/2017  05:13 PM    <DIR>          electron-inspector
01/13/2017  06:53 PM    <DIR>          electron-packager
01/14/2017  05:09 PM    <DIR>          electron-rebuild
01/13/2017  06:50 PM    <DIR>          express
01/13/2017  06:49 PM    <DIR>          knex
01/13/2017  06:49 PM    <DIR>          sqlite3
               0 File(s)              0 bytes
              12 Dir(s)  407,370,067,968 bytes free

Kyle@DevMachine C:\git\manymore
> dir node_modules\electron-inspector
 Volume in drive C is OSDisk
 Volume Serial Number is A62D-5055

 Directory of C:\git\manymore\node_modules\electron-inspector

01/14/2017  05:13 PM    <DIR>          .
01/14/2017  05:13 PM    <DIR>          ..
01/14/2017  05:13 PM                18 .gitattributes
01/14/2017  05:13 PM                18 .npmignore
01/14/2017  05:13 PM    <DIR>          bin
01/14/2017  05:13 PM    <DIR>          lib
01/14/2017  05:13 PM             1,091 LICENSE
01/14/2017  05:14 PM    <DIR>          node_modules
01/14/2017  05:13 PM               667 npm-shrinkwrap.json
01/14/2017  05:13 PM             2,208 package.json
01/14/2017  05:13 PM             6,550 README.md
               6 File(s)         10,552 bytes
               5 Dir(s)  407,369,924,608 bytes free

Kyle@DevMachine C:\git\manymore
> dir node_modules\electron-inspector\node_modules
 Volume in drive C is OSDisk
 Volume Serial Number is A62D-5055

 Directory of C:\git\manymore\node_modules\electron-inspector\node_modules

01/14/2017  05:14 PM    <DIR>          .
01/14/2017  05:14 PM    <DIR>          ..
01/14/2017  05:14 PM    <DIR>          .bin
01/14/2017  05:14 PM    <DIR>          node-inspector
01/14/2017  05:14 PM    <DIR>          v8-debug
01/14/2017  05:14 PM    <DIR>          v8-profiler
               0 File(s)              0 bytes
               6 Dir(s)  407,369,924,608 bytes free

Kyle@DevMachine C:\git\manymore
> .\node_modules\.bin\electron-inspector
module.js:327
    throw err;
    ^

Error: Cannot find module 'yargs'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\git\manymore\node_modules\electron-inspector\lib\cli.js:4:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

Kyle@DevMachine C:\git\manymore
>
```

**Comment by enlight** [comment]
Which version of Node and NPM are you using?

**Comment by kpatrick** [comment]
Kyle@DevMachine C:\git\manymore
> npm --version
2.15.11

Kyle@DevMachine C:\git\manymore
> node --version
v4.7.1

**Comment by enlight** [comment]
That NPM version is way too old, you need to upgrade to v3 or later.

**Comment by kpatrick** [comment]
Thanks. Closing.
