### ISSUE TITLE
Compatibility issues with electron-rebuild@1.5.x

### ISSUE THREAD

**Issue by msemenistyi** [enlight/electron-inspector#7]
Failed to load electron-prebuilt, abandoning rebuild. 

{ Error: Cannot find module 'electron-rebuild/lib/node-pre-gyp-fix'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
...

**Comment by enlight** [comment]
Yeah, there were a few breaking changes to the `electron-rebuild` API, I think the last version that works is 1.2.1. Unfortunately I don't have the time to fix this right now.

**Comment by AugustSaintFreytag** [comment]
This information should be written in gigantic red letters as it applies to all new installations that'd be automatically their respective latest versions. Thanks for enlightening me!

```
npm install electron-rebuild@1.2.1 --save-dev
./node_modules/.bin/electron-inspector
```

It automatically rebuilds as necessary and launches directly.
