### ISSUE TITLE
cannot install electron-inspector

### ISSUE THREAD

**Issue by adarrra** [enlight/electron-inspector#8]
hi! can you help me to understand what the problem is? 
I have this output:

```bash
> v8-debug@0.7.7 preinstall /home/adara/webdev/electron/d-pad/node_modules/.staging/v8-debug-7f3eec18
> node -e 'process.exit(0)'


> v8-profiler@5.6.5 preinstall /home/adara/webdev/electron/d-pad/node_modules/.staging/v8-profiler-ba7fd586
> node -e 'process.exit(0)'


> v8-debug@0.7.7 install /home/adara/webdev/electron/d-pad/node_modules/electron-inspector/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v0.7.7/node-v51-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@0.7.7 and node@7.7.1 (node-v51 ABI) (falling back to source compile with node-gyp) 
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory '/home/adara/webdev/electron/d-pad/node_modules/electron-inspector/node_modules/v8-debug/build'
  CXX(target) Release/obj.target/debug/src/debug.o
../src/debug.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE nodex::Debug::Call(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/debug.cc:38:27: error: no matching function for call to ‘v8::Debug::Call(v8::Local<v8::Function>&)’
         v8::Debug::Call(fn);
                           ^
In file included from ../src/debug.cc:1:0:
/home/adara/.node-gyp/7.7.1/include/node/v8-debug.h:198:28: note: candidate: static v8::MaybeLocal<v8::Value> v8::Debug::Call(v8::Local<v8::Context>, v8::Local<v8::Function>, v8::Local<v8::Value>)
   static MaybeLocal<Value> Call(Local<Context> context,
                            ^
/home/adara/.node-gyp/7.7.1/include/node/v8-debug.h:198:28: note:   candidate expects 3 arguments, 1 provided
../src/debug.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE nodex::Debug::SendCommand(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/debug.cc:46:61: error: no matching function for call to ‘v8::Debug::GetDebugContext()’
         Isolate* debug_isolate = v8::Debug::GetDebugContext()->GetIsolate(
                                                             ^
In file included from ../src/debug.cc:1:0:
/home/adara/.node-gyp/7.7.1/include/node/v8-debug.h:248:25: note: candidate: static v8::Local<v8::Context> v8::Debug::GetDebugContext(v8::Isolate*)
   static Local<Context> GetDebugContext(Isolate* isolate);
                         ^
/home/adara/.node-gyp/7.7.1/include/node/v8-debug.h:248:25: note:   candidate expects 1 argument, 0 provided
../src/debug.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE nodex::Debug::RunScript(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/debug.cc:61:67: error: no matching function for call to ‘v8::Debug::GetDebugContext()’
         Local<Context> debug_context = v8::Debug::GetDebugContext();
                                                                   ^
In file included from ../src/debug.cc:1:0:
/home/adara/.node-gyp/7.7.1/include/node/v8-debug.h:248:25: note: candidate: static v8::Local<v8::Context> v8::Debug::GetDebugContext(v8::Isolate*)
   static Local<Context> GetDebugContext(Isolate* isolate);
                         ^
/home/adara/.node-gyp/7.7.1/include/node/v8-debug.h:248:25: note:   candidate expects 1 argument, 0 provided
../src/debug.cc:66:54: error: no matching function for call to ‘v8::Debug::GetDebugContext()’
           debug_context = v8::Debug::GetDebugContext();
                                                      ^
In file included from ../src/debug.cc:1:0:
/home/adara/.node-gyp/7.7.1/include/node/v8-debug.h:248:25: note: candidate: static v8::Local<v8::Context> v8::Debug::GetDebugContext(v8::Isolate*)
   static Local<Context> GetDebugContext(Isolate* isolate);
                         ^
/home/adara/.node-gyp/7.7.1/include/node/v8-debug.h:248:25: note:   candidate expects 1 argument, 0 provided
debug.target.mk:97: recipe for target 'Release/obj.target/debug/src/debug.o' failed
make: *** [Release/obj.target/debug/src/debug.o] Error 1
make: Leaving directory '/home/adara/webdev/electron/d-pad/node_modules/electron-inspector/node_modules/v8-debug/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/adara/webdev/electron/d-pad/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-64-generic
gyp ERR! command "/home/adara/.nvm/versions/node/v7.7.1/bin/node" "/home/adara/webdev/electron/d-pad/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/adara/webdev/electron/d-pad/node_modules/electron-inspector/node_modules/v8-debug/build/debug/v0.7.7/node-v51-linux-x64/debug.node" "--module_name=debug" "--module_path=/home/adara/webdev/electron/d-pad/node_modules/electron-inspector/node_modules/v8-debug/build/debug/v0.7.7/node-v51-linux-x64"
gyp ERR! cwd /home/adara/webdev/electron/d-pad/node_modules/electron-inspector/node_modules/v8-debug
gyp ERR! node -v v7.7.1
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/adara/.nvm/versions/node/v7.7.1/bin/node /home/adara/webdev/electron/d-pad/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/adara/webdev/electron/d-pad/node_modules/electron-inspector/node_modules/v8-debug/build/debug/v0.7.7/node-v51-linux-x64/debug.node --module_name=debug --module_path=/home/adara/webdev/electron/d-pad/node_modules/electron-inspector/node_modules/v8-debug/build/debug/v0.7.7/node-v51-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/adara/webdev/electron/d-pad/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:899:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 4.4.0-64-generic
node-pre-gyp ERR! command "/home/adara/.nvm/versions/node/v7.7.1/bin/node" "/home/adara/webdev/electron/d-pad/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/adara/webdev/electron/d-pad/node_modules/electron-inspector/node_modules/v8-debug
node-pre-gyp ERR! node -v v7.7.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.33
node-pre-gyp ERR! not ok 
Failed to execute '/home/adara/.nvm/versions/node/v7.7.1/bin/node /home/adara/webdev/electron/d-pad/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/adara/webdev/electron/d-pad/node_modules/electron-inspector/node_modules/v8-debug/build/debug/v0.7.7/node-v51-linux-x64/debug.node --module_name=debug --module_path=/home/adara/webdev/electron/d-pad/node_modules/electron-inspector/node_modules/v8-debug/build/debug/v0.7.7/node-v51-linux-x64' (1)
d-pad@0.0.1 /home/adara/webdev/electron/d-pad
└── (empty)

npm WARN d-pad@0.0.1 No repository field.
npm ERR! Linux 4.4.0-64-generic
npm ERR! argv "/home/adara/.nvm/versions/node/v7.7.1/bin/node" "/home/adara/.nvm/versions/node/v7.7.1/bin/npm" "install" "electron-inspector" "--save-dev"
npm ERR! node v7.7.1
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! v8-debug@0.7.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-debug@0.7.7 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs v8-debug
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/adara/webdev/electron/d-pad/npm-debug.log
```

**Comment by dougludlow** [comment]
Seeing the same issue on macOS 10.12.3.

**Comment by AuHau** [comment]
I see that you are running also almost latest version of node. Try to downgrade to 6.5.0, according to [this comment](https://github.com/node-inspector/v8-debug/issues/7#issuecomment-261641526) that should help. At least that helped me, although I got stuck on some other problem :disappointed:

**Comment by pravipati** [comment]
```
node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v0.7.7/electron-v1.6-darwin-x64.tar.gz 
```
Running into the same issue. Tried downgrading per @AuHau's comment, but that didn't work. Any other 💡s? From my `npm-debug.log` 👇 

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/pravipati/.nvm/versions/node/v6.5.0/bin/node',
1 verbose cli   '/Users/pravipati/Documents/Code/GitNotes/node_modules/npm/bin/npm-cli.js',
1 verbose cli   'rebuild',
1 verbose cli   'v8-debug',
1 verbose cli   '--runtime=electron',
1 verbose cli   '--target=1.6.2',
1 verbose cli   '--arch=x64' ]
2 info using npm@3.10.10
3 info using node@v6.5.0
4 info readInstalled object
5 verbose rebuild path, id [ '/Users/pravipati/Documents/Code/GitNotes/node_modules/electron-inspector/node_modules/v8-debug',
5 verbose rebuild   'v8-debug@0.7.7' ]
6 silly rebuild set [ '/Users/pravipati/Documents/Code/GitNotes/node_modules/electron-inspector/node_modules/v8-debug' ]
7 info build /Users/pravipati/Documents/Code/GitNotes/node_modules/electron-inspector/node_modules/v8-debug
8 info lifecycle v8-debug@0.7.7~preinstall: v8-debug@0.7.7
9 verbose lifecycle v8-debug@0.7.7~preinstall: unsafe-perm in lifecycle true
10 verbose lifecycle v8-debug@0.7.7~preinstall: PATH: /Users/pravipati/Documents/Code/GitNotes/node_modules/npm/bin/node-gyp-bin:/Users/pravipati/Documents/Code/GitNotes/node_modules/electron-inspector/node_modules/v8-debug/node_modules/.bin:/Users/pravipati/Documents/Code/GitNotes/node_modules/electron-inspector/node_modules/.bin:/Users/pravipati/Documents/Code/GitNotes/node_modules/.bin:/Users/pravipati/.nvm/versions/node/v6.5.0/bin:/Users/pravipati/.rvm/gems/ruby-2.3.1/bin:/Users/pravipati/.rvm/gems/ruby-2.3.1@global/bin:/Users/pravipati/.rvm/rubies/ruby-2.3.1/bin:/usr/local/opt/node@6/bin:/Users/pravipati/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/pravipati/.rvm/bin
11 verbose lifecycle v8-debug@0.7.7~preinstall: CWD: /Users/pravipati/Documents/Code/GitNotes/node_modules/electron-inspector/node_modules/v8-debug
12 silly lifecycle v8-debug@0.7.7~preinstall: Args: [ '-c', 'node -e \'process.exit(0)\'' ]
13 silly lifecycle v8-debug@0.7.7~preinstall: Returned: code: 0  signal: null
14 info linkStuff v8-debug@0.7.7
15 silly linkStuff v8-debug@0.7.7 has /Users/pravipati/Documents/Code/GitNotes/node_modules/electron-inspector/node_modules as its parent node_modules
16 verbose linkBins v8-debug@0.7.7
17 verbose linkMans v8-debug@0.7.7
18 verbose rebuildBundles v8-debug@0.7.7
19 info lifecycle v8-debug@0.7.7~install: v8-debug@0.7.7
20 verbose lifecycle v8-debug@0.7.7~install: unsafe-perm in lifecycle true
21 verbose lifecycle v8-debug@0.7.7~install: PATH: /Users/pravipati/Documents/Code/GitNotes/node_modules/npm/bin/node-gyp-bin:/Users/pravipati/Documents/Code/GitNotes/node_modules/electron-inspector/node_modules/v8-debug/node_modules/.bin:/Users/pravipati/Documents/Code/GitNotes/node_modules/electron-inspector/node_modules/.bin:/Users/pravipati/Documents/Code/GitNotes/node_modules/.bin:/Users/pravipati/.nvm/versions/node/v6.5.0/bin:/Users/pravipati/.rvm/gems/ruby-2.3.1/bin:/Users/pravipati/.rvm/gems/ruby-2.3.1@global/bin:/Users/pravipati/.rvm/rubies/ruby-2.3.1/bin:/usr/local/opt/node@6/bin:/Users/pravipati/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/pravipati/.rvm/bin
22 verbose lifecycle v8-debug@0.7.7~install: CWD: /Users/pravipati/Documents/Code/GitNotes/node_modules/electron-inspector/node_modules/v8-debug
23 silly lifecycle v8-debug@0.7.7~install: Args: [ '-c', 'node-pre-gyp install --fallback-to-build' ]
24 silly lifecycle v8-debug@0.7.7~install: Returned: code: 1  signal: null
25 info lifecycle v8-debug@0.7.7~install: Failed to exec install script
26 verbose stack Error: v8-debug@0.7.7 install: `node-pre-gyp install --fallback-to-build`
26 verbose stack Exit status 1
26 verbose stack     at EventEmitter.<anonymous> (/Users/pravipati/Documents/Code/GitNotes/node_modules/npm/lib/utils/lifecycle.js:255:16)
26 verbose stack     at emitTwo (events.js:106:13)
26 verbose stack     at EventEmitter.emit (events.js:191:7)
26 verbose stack     at ChildProcess.<anonymous> (/Users/pravipati/Documents/Code/GitNotes/node_modules/npm/lib/utils/spawn.js:40:14)
26 verbose stack     at emitTwo (events.js:106:13)
26 verbose stack     at ChildProcess.emit (events.js:191:7)
26 verbose stack     at maybeClose (internal/child_process.js:877:16)
26 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
27 verbose pkgid v8-debug@0.7.7
28 verbose cwd /Users/pravipati/Documents/Code/GitNotes/node_modules/electron-inspector/node_modules
29 error Darwin 15.6.0
30 error argv "/Users/pravipati/.nvm/versions/node/v6.5.0/bin/node" "/Users/pravipati/Documents/Code/GitNotes/node_modules/npm/bin/npm-cli.js" "rebuild" "v8-debug" "--runtime=electron" "--target=1.6.2" "--arch=x64"
31 error node v6.5.0
32 error npm  v3.10.10
33 error code ELIFECYCLE
34 error v8-debug@0.7.7 install: `node-pre-gyp install --fallback-to-build`
34 error Exit status 1
35 error Failed at the v8-debug@0.7.7 install script 'node-pre-gyp install --fallback-to-build'.
35 error Make sure you have the latest version of node.js and npm installed.
35 error If you do, this is most likely a problem with the v8-debug package,
35 error not with npm itself.
35 error Tell the author that this fails on your system:
35 error     node-pre-gyp install --fallback-to-build
35 error You can get information on how to open an issue for this project with:
35 error     npm bugs v8-debug
35 error Or if that isn't available, you can get their info via:
35 error     npm owner ls v8-debug
35 error There is likely additional logging output above.
36 verbose exit [ 1, true ]
```

**Comment by simon-asp** [comment]
got the same error on mac os 10.12.5

**Comment by enlight** [comment]
As of Electron 1.7.2 Beta you should use the built-in debugger with the [`--inspect`/`--inspect-brk` flags](https://github.com/electron/electron/pull/9473) and forget about `node-inspector` and `electron-inspector`.
